### ISSUE TITLE
artifically low output

### ISSUE THREAD

**Issue by DarkJester** [initstring/linkedin2username#7] opened 2018-03-16 21:31 UTC
shows only 25 results of over 16k results using linkedin by web browser shows the 16k+ plus users

[+] Starting search....

[+] Company has 16050 profiles to check. Some may be anonymous.
[+] Setting search to 643 loops of 25 results each.

[+] OK, looking for results on loop numer 1
    [+] Added 25 new names.
[+] OK, looking for results on loop numer 2
[+] We have hit the end of the road! Moving on...

All done! Check out your lovely new files.

**Comment by initstring** [comment] 2018-03-16 21:34
Thanks for taking the time to open an issue!

I'd like to try to recreate this. Would you be able to share the company name with me? If you prefer not to post it on here, you can email me at my github username at protonmail.com.

Thank you!!!

**Comment by DarkJester** [comment] 2018-03-16 21:46
please provide your email address. i can not disclose in public

**Comment by initstring** [comment] 2018-03-16 21:47
No worries. It's the same as my github username (initstring) using the protonmail.com domain.

**Comment by initstring** [comment] 2018-03-17 01:27
I am unable to reproduce the issue, I've confirmed the tools works as expected with the specified company so will close this issue for now.

If I hear about this happening more, I will look into adding a debug flag to help track it down.

Thanks!

**Closed as completed by initstring** 2018-03-17 01:27 UTC
