### ISSUE TITLE
Yikes, got an HTTP 400. This is not normal

### ISSUE THREAD

**Issue by gusmaocool** [initstring/linkedin2username#72] opened 2023-10-05 20:52 UTC
Hi everyone!

After starting the tool, it brought me this message. "Yikes, got an HTTP 400. This is not normal" What does that mean?

**Comment by initstring** [comment] 2023-10-05 21:11
Hi @gusmaocool, thanks for opening an issue!

Can you please provide more details? Please share the commands you ran, what you did when the browser window popped open, the full text output from the console, and anything else think might be helpful.

You can obfuscate anything sensitive, like company names etc.

**Comment by gusmaocool** [comment] 2023-10-05 21:22
I am using Macbook M2 pro with ARM architecture. After I execute the command, the browser opens to the Linkedin login screen and I enter the credentials. I am logged in and leave the browser open. Then I press "Enter" and then it brings me this answer.
<img width="761" alt="Screenshot 2023-10-05 at 18 14 14" src="https://github.com/initstring/linkedin2username/assets/28679008/dc0d2543-5d36-461a-8e5c-de9803a78a5b">

**Comment by initstring** [comment] 2023-10-05 21:35
Thanks for this!

It looks like it is logging in ok and grabbing your session cookies, as it has no problem getting the company info. The problem then is some sort of bad request when looping through the employees.

I tested the program myself right now, and I don't get the error. It completes ok. So at least LinkedIn hasn't totally blocked the tool. I'm also on an ARM-based Mac.

I'm not sure why you are getting this. You can troubleshoot a bit more using the "--proxy" flag to proxy your loops through Burp or Zap or something. If you spot something with the requests that looks off, and have an idea for a fix, can you let me know?

I'll leave this issue open, to see if others start experiencing the same problem too.

**Comment by rbtoms** [comment] 2023-10-06 00:02
It looks like I'm running into the same issue. Using "Google" as an example, it seems to result in an HTTP 400 response on the second API request. If it helps, I'm running an Intel-based MacOS architecture.

![2023-10-05_16-00-33](https://github.com/initstring/linkedin2username/assets/54727767/6f90bd31-79d5-42b0-9735-0c5e51158ad2)

![2023-10-05_15-58-57](https://github.com/initstring/linkedin2username/assets/54727767/c5c2f54d-1cb3-4dfd-be99-9c7b939dc96a)

**Comment by initstring** [comment] 2023-10-06 04:10
Thanks @rbtoms! This helps and I can now reproduce the issue. Looking into it...

**Comment by initstring** [comment] 2023-10-06 04:36
I see when proxying normal traffic to LinkedIn that they are now using a graphql API endpoint that isn't so easy to understand. The queries don't take recognisable values. I noticed this a couple months ago, but the endpoints this tool was using were still available.

It's possible LinkedIn has deprecated the endpoints.

I don't think I will have time to troubleshoot this for a while. Probably the fix is one of:

- Figure out this new graphql endpoint, and modify the tool to use it
- Figure out some new random syntax or header or something required to continue using the old endpoint

**Comment by initstring** [comment] 2023-10-06 06:01
I just found this project that was previously using the same API as this tool. Their tool also broke, and it was indeed due to a transition to the graphql API.

Probably by looking at their diffs, it would be possible to see what needs fixing in linkedin2username: https://github.com/tomquirk/linkedin-api/pull/332/files

If anyone sees this issue, and has time to work on this, I would gladly review the pull request. It's just the "search" API that needs to be updated in linkedin2username, which is used in the [get_results function](https://github.com/initstring/linkedin2username/blob/master/linkedin2username.py#L444).

Thanks!

**Comment by coj337** [comment] 2023-10-10 05:36
I needed this today so I'm just tidying up my patch, PR incoming soon!

**Comment by initstring** [comment] 2023-10-11 00:55
Thanks @coj337 for your great contribution. I've merged it into a separate branch so I can get it working with the unit tests. Further work will happen in linked PR.

**Closed as completed** 2023-10-11 03:39 UTC
Labels: help wanted
